/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HdiSensor
 * @{
 *
 * @brief Provides unified APIs for sensor services to access sensor drivers.
 *
 * A sensor service can obtain a sensor driver object or agent and then call APIs provided by this object or agent to
 * access different types of sensor devices based on the sensor IDs, thereby obtaining sensor information,
 * subscribing to or unsubscribing from sensor data, enabling or disabling a sensor,
 * setting the sensor data reporting mode, and setting sensor options such as the accuracy and measurement range.
 *
 * @since 6.1
 */

/**
 * @file ISensorTransformInterfaces.idl
 *
 * @brief Declares the APIs provided by the sensor module for obtaining sensor information, subscribing to or
 * unsubscribing from sensor data, enabling or disabling a sensor, setting the sensor data reporting mode,
 * and setting sensor options such as the accuracy and measurement range.
 *
 * @since 6.1
 * @version 3.1
 */

package ohos.hdi.sensor.transform.v1_0;

import ohos.hdi.sensor.transform.v1_0.ISensorTransformTypes;

/**
 * @brief Defines the functions for performing basic operations on sensors.
 *
 * The operations include obtaining sensor information, subscribing to or unsubscribing from sensor data,
 * enabling or disabling a sensor, setting the sensor data reporting mode, and setting sensor options such as
 * the accuracy and measurement range.
 */

interface ISensorTransformInterfaces {
    /**
     * @brief Enables the sensor available in the sensor list based on the specified sensor ID.
     * The subscriber can obtain the sensor data only after the sensor is enabled.
     *
     * @param sensorId Indicates the sensor ID. For details, see {@link SensorTypeTag}.
     * @param deviceId Indicates the device ID. For details, see {@link SensorTypeTag}.
     * @param callbackId Indicates the operation is on the callback object bound to Register.
     * @return Returns <b>0</b> if the sensor is successfully enabled; returns a negative value otherwise.
     *
     * @since 6.0
     * @version 1.0
     */
    ConvertSensorData([in] struct HdfDeviceStatusPolicy status, [in] struct HdfSensorData inSensorData,
        [out] struct HdfSensorData outSensorData);
}
