/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HdiBluetoothLpBle
 * @{
 *
 * @brief Provides APIs for the low power BLE service.
 *
 * @since 5.0
 * @version 1.0
 */

/**
 * @file IBleCallback.idl
 *
 * @brief Declares the callbacks for the low power BLE module.
 *
 * @since 5.0
 * @version 1.0
 */

/**
 * @brief Declares the path of the low power BLE module interface package.
 *
 * @since 5.0
 */
package ohos.hdi.bluetooth.lp_ble.v1_0;

/**
 * @brief Defines the message callback for the low power BLE module.
 *
 * Before enabling the low power BLE feature, you need to register this callback to report the information.
 * For details, see {@link IBleInterface}.
 *
 * @since 5.0
 */
[callback] interface IBleCallback {
    /**
     * @brief Called to report the message data sent by the controller.
     *
     *
     *
     * @param message Indicates the data report.
     *
     * @return Returns <b>0</b> if the operation is successful.
     * @return Returns a negative value if the operation fails.
     *
     * @since 5.0
     * @version 1.0
     */
    [oneway] OnMessageCallback([in] unsigned char[] message);

    /**
     * @brief Called to report the device list sent by the controller.
     *
     *
     *
     * @param deviceList Indicates the device list report.
     *
     * @return Returns <b>0</b> if the operation is successful.
     * @return Returns a negative value if the operation fails.
     *
     * @since 5.0
     * @version 1.0
     */
    [oneway] OnDeviceListCallback([in] unsigned char[] deviceList);
}
