/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 /**
 * @addtogroup HdiLpfenceMntn
 * @{
 *
 * @brief Provides lpfence mntn APIs for the lpfence mntn service.
 *
 * @since 6.0
 * @version 1.0
 */

/**
 * @file IMntnCallback.idl
 *
 * @brief Declares the callbacks for the lpfence mntn module.
 *
 * @since 6.0
 * @version 1.0
 */

/**
 * @brief Declares the path of the lpfence mntn module interface package.
 *
 * @since 6.0
 */
package ohos.hdi.location.lpfence.mntn.v1_0;

/**
 * @brief Imports data types of the lpfence mntn module.
 *
 * @since 6.0
 */
import ohos.hdi.location.lpfence.mntn.v1_0.MntnTypes;

/**
 * @brief Defines the callback for the lpfence mntn module.
 *
 * Before enabling the lpfence mntn feature, you need to register this callback to report the device has obtained the lpfence mntn information.
 * For details, see {@link IMntnInterface}.
 *
 * @since 6.0
 */
[callback] interface IMntnCallback {
    /**
     * @brief Called to report the lpfence mntn request result.
     *
     *
     *
     * @param mntnInfo Indicates the result of getting lpfence mntn.
     *
     * @return Returns <b>0</b> if the callback is invoked successfully.
     * @return Returns a negative value if the callback fails to be invoked.
     *
     @since 6.0
     */
    OnLpfenceMntnRequestCb([in] String[] mntnInfo);
}
/** @} */
