/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HdiSensor
 * @{
 *
 * @brief Provides unified APIs for sensor services to access sensor drivers.
 *
 * A sensor service can obtain a sensor driver object or agent and then call APIs provided by this object or agent to
 * access different types of sensor devices based on the sensor IDs, thereby obtaining sensor information,
 * subscribing to or unsubscribing from sensor data, enabling or disabling a sensor,
 * setting the sensor data reporting mode, and setting sensor options such as the accuracy and measurement range.
 *
 * @version 3.1
 */

/**
 * @file SensorTypes.idl
 *
 * @brief Defines the data used by the sensor module, including the sensor information,
 * and reported sensor data.
 *
 * @since 6.0
 * @version 3.1
 */

package ohos.hdi.sensor.v3_1;

/**
 * @brief Indicates the id of callback.
 *
 * @since 6.0
 * @version 1.0
 */
enum CallbackId {
    CALLBACK_ID_BEGIN = 100000,     /**< Indicates the min callbackId */
    GPS_CALLBACK_ID_BEGIN = 100001, /**< Indicates the begin callbackId of gps */
    GPS_CALLBACK_ID_END = 100010, /**< Indicates the end callbackId of gps */
    THP_CALLBACK_ID_BEGIN = 100011, /**< Indicates the begin callbackId of thp */
    THP_CALLBACK_ID_END = 100020, /**< Indicates the end callbackId of thp */
    CALLBACK_ID_END,
};