/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup power
 * @{
 *
 * @brief Provides APIs for performing suspend/wakeup operations, subscribing to the suspend/wakeup state,
 * and managing running locks.
 * 
 * After obtaining an object or proxy of this module, the power service can invoke related APIs to perform
 * suspend/wakeup operations, subscribe to the suspend/wakeup state, and manage running locks.
 *
 * @since 3.1
 * @version 1.1
 */

/**
 * @file IPowerInterface.idl
 *
 * @brief Provides APIs for performing suspend/wakeup operations, subscribing to the suspend/wakeup state,
 * and managing running locks.
 *
 * 
 *
 * @since 3.1
 * @version 1.1
 */

package ohos.hdi.power.v1_4;

import ohos.hdi.power.v1_3.IPowerInterface;

/**
 * @brief Represents APIs for performing suspend/wakeup operations, subscribing to the suspend/wakeup state,
 * and managing running locks.
 *
 * @since 3.1
 * @version 1.1
 */
interface IPowerInterface extends ohos.hdi.power.v1_3.IPowerInterface {
    /**
     * @brief Forces the device to suspend, ignoring all wakelocks and wakeup_count checks.
     *
     * This API directly writes the tag to /sys/power/state to trigger kernel suspend,
     * bypassing the AutoSuspendLoop's wakeup_count race condition check.
     * It does not notify HDI callbacks (the caller is responsible for callback notification).
     *
     * @param tag Suspend type tag, "mem" for S3 suspend, "ulsr" for ulsr mode.
     * @return Returns <b>HDF_SUCCESS</b> if the operation is successful.
     *
     * @since 7.0
     * @version 1.0
     */
    ForceSuspendIgnoringWakelock([in] String tag);
}
/** @} */
