/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup battery
 * @{
 *
 * @brief 提供获取、订阅电池信息的接口。
 *
 * @since 3.1
 * @version 1.0
 */

/**
 * @file Types.idl
 *
 * @brief 电池信息相关数据类型。
 *
 * 电池信息中使用的数据类型, 包括健康状态，充电状态，充电设备类型和电池信息结构。
 *
 * @since 3.1
 * @version 1.0
 */
package ohos.hdi.battery.v1_0;


/**
 * @brief 电池的健康状态
 */
enum BatteryHealthState
{
    /** 表示电池健康状态未知 */
    BATTERY_HEALTH_UNKNOWN = 0,
    /** 表示电池健康状态为正常 */
    BATTERY_HEALTH_GOOD,
    /** 表示电池健康状态为过热 */
    BATTERY_HEALTH_OVERHEAT,
    /** 表示电池健康状态为过压 */
    BATTERY_HEALTH_OVERVOLTAGE,
    /** 表示电池健康状态为低温 */
    BATTERY_HEALTH_COLD,
    /** 表示电池健康状态为僵死 */
    BATTERY_HEALTH_DEAD,
    /** 保留位 */
    BATTERY_HEALTH_RESERVED,
};

/**
 * @brief 电池的充电状态
 */
enum BatteryChargeState
{
    /** 表示电池充电状态未知 */
    CHARGE_STATE_NONE = 0,
    /** 表示电池充电状态为使能状态 */
    CHARGE_STATE_ENABLE,
    /** 表示电池充电状态为停止状态 */
    CHARGE_STATE_DISABLE,
    /** 表示电池充电状态为已充满状态 */
    CHARGE_STATE_FULL,
    /** 保留位 */
    CHARGE_STATE_RESERVED,
};

/**
 * @brief 电池的充电设备类型
 */
enum BatteryPluggedType
{
    /** 表示连接充电器类型未知 */
    PLUGGED_TYPE_NONE = 0,
    /** 表示连接的充电器类型为交流充电器 */
    PLUGGED_TYPE_AC,
    /** 表示连接的充电器类型为USB */
    PLUGGED_TYPE_USB,
    /** 表示连接的充电器类型为无线充电器 */
    PLUGGED_TYPE_WIRELESS,
    /** 截止位 */
    PLUGGED_TYPE_BUTT
};

/**
 * @brief 电池相关信息
 */
struct BatteryInfo {
    /** 表示电池的电量百分比 */
    int capacity;
    /** 表示电池的电压 */
    int voltage;
    /** 表示电池的温度 */
    int temperature;
    /** 表示电池的健康状态 */
    int healthState;
    /** 表示电池的充电设备类型 */
    int pluggedType;
    /** 表示电池的最大充电电流 */
    int pluggedMaxCurrent;
    /** 表示电池的最大充电电压 */
    int pluggedMaxVoltage;
    /** 表示电池的充电状态 */
    int chargeState;
    /** 表示电池的充电次数 */
    int chargeCounter;
    /** 表示电池的总容量 */
    int totalEnergy;
    /** 表示电池的平均电流 */
    int curAverage;
    /** 表示电池的实时电流 */
    int curNow;
    /** 表示电池的剩余容量 */
    int remainEnergy;
    /** 表示是否支持电池或者电池是否在位 */
    byte present;
    /** 表示电池的技术型号 */
    String technology;
};
/** @} */
