/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.nnrt.v2_1;

import ohos.hdi.nnrt.v2_1.NnrtTypes;
import ohos.hdi.nnrt.v2_0.NodeAttrTypes;

struct Abs
{
};

struct BroadcastTo
{
    long[] shape;
};

struct Clip
{
    float max;
    float min;
};

struct ConstantOfShape
{
    long data_type;
    float[] value;
};

struct DepthToSpace
{
    long block_size;
    enum Format format;
    String mode;
};

struct Equal
{
};

struct ExpFusion
{
    float base;
    float scale;
    float shift;
};

struct Flatten
{
    long axis;
};

struct Greater
{
};

struct GreaterEqual
{
};

struct InstanceNorm
{
    float epsilon;
};

struct LeakyRelu
{
    float negative_slope;
};

struct Less
{
};

struct LSTM
{
    boolean bidirectional;
    boolean has_bias;
    long input_size;
    long hidden_size;
    long num_layers;
    long num_directions;
    float dropout;
    float zoneout_cell;
    float zoneout_hidden;
    long proj_size;
};

struct NotEqual
{
};

struct Range
{
    long d_type;
    long start;
    long limit;
    long delta;
};

struct RealDiv
{
};

struct Square
{
};

struct Unstack
{
    long axis;
};

struct Select
{
};

struct Erf
{
};