/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file icamera_host.h
 *
 * @brief Management class of the camera service that provides Hardware Driver Interfaces (HDIs) for the upper layer.
 *
 * @since 6.1
 * @version 1.4
 */

package ohos.hdi.camera.v1_5;

import ohos.hdi.camera.v1_3.ICameraHost;
import ohos.hdi.camera.v1_5.ICameraDevice;
import ohos.hdi.camera.v1_5.Types;
import ohos.hdi.camera.v1_0.ICameraDeviceCallback;

interface ICameraHost extends ohos.hdi.camera.v1_3.ICameraHost {
    /**
     * @brief Opens a camera device.
     *
     * By calling this function, you can obtain the <b>ICameraDevice</b> instance and operate the
     * specific camera device mapping to the instance.
     *
     * @param cameraId Indicates the ID of the camera device, which can be obtained by calling {@link GetCameraIds}.
     * @param callback Indicates the callback related to the camera. For details, see {@link ICameraDeviceCallback}.
     * @param device Indicates the <b>ICameraDevice</b> instance corresponding to the ID of the camera device.
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    OpenCamera_V1_4([in] String cameraId, [in] ICameraDeviceCallback callbackObj, [out] ICameraDevice device);

    /**
     * @brief Opens a camera device in secure mode.
     *
     * By calling this function, you can obtain the <b>ICameraDevice</b> instance and operate the
     * specific camera device mapping to the instance.
     *
     * @param cameraId Indicates the ID of the camera device, which can be obtained by calling {@link GetCameraIds}.
     * @param callback Indicates the callback related to the camera. For details, see {@link ICameraDeviceCallback}.
     * @param device Indicates the <b>ICameraDevice</b> instance corresponding to the ID of the camera device.
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    OpenSecureCamera_V1_4([in] String cameraId, [in] ICameraDeviceCallback callbackObj, [out] ICameraDevice device);

    /**
     * @brief EntireClose a camera.
     *
     * @param cameraId Indicates the ID of the camera device, which can be obtained by calling {@link GetCameraIds}.
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    EntireCloseDevice([in] String cameraId);

    /**
     * @brief Get camera storage size.
     *
     * @param userId userId
     * @param storageSize camera storage size
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    GetCameraStorageSize([in] int userId, [out] long storageSize);

    /**
     * @brief Opens a camera device.
     *
     * By calling this function, you can obtain the <b>ICameraDevice</b> instance and operate the
     * specific camera device mapping to the instance.
     *
     * @param cameraId Indicates the ID of the camera device, which can be obtained by calling {@link GetCameraIds}.
     * @param callback Indicates the callback related to the camera. For details, see {@link ICameraDeviceCallback}.
     * @param device Indicates the <b>ICameraDevice</b> instance corresponding to the ID of the camera device.
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    OpenCamera_V1_5([in] String cameraId, [in] ICameraDeviceCallback callbackObj, [out] ICameraDevice device);

    /**
     * @brief Opens a camera device in secure mode.
     *
     * By calling this function, you can obtain the <b>ICameraDevice</b> instance and operate the
     * specific camera device mapping to the instance.
     *
     * @param cameraId Indicates the ID of the camera device, which can be obtained by calling {@link GetCameraIds}.
     * @param callback Indicates the callback related to the camera. For details, see {@link ICameraDeviceCallback}.
     * @param device Indicates the <b>ICameraDevice</b> instance corresponding to the ID of the camera device.
     *
     * @return Returns <b>NO_ERROR</b> if the operation is successful; returns an error code defined
     * in {@link CamRetCode} otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    OpenSecureCamera_V1_5([in] String cameraId, [in] ICameraDeviceCallback callbackObj, [out] ICameraDevice device);
}