/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HdiSensor
 * @{
 *
 * @brief Provides unified APIs for sensor services to access sensor drivers.
 *
 * A sensor service can obtain a sensor driver object or agent and then call APIs provided by this object or agent to
 * access different types of sensor devices based on the sensor IDs, thereby obtaining sensor information,
 * subscribing to or unsubscribing from sensor data, enabling or disabling a sensor,
 * setting the sensor data reporting mode, and setting sensor options such as the accuracy and measurement range.
 *
 * @since 6.1
 */

/**
 * @file ISensorconvertInterfaces.idl
 *
 * @brief Declares the APIs provided by the sensor module for obtaining sensor information, subscribing to or
 * unsubscribing from sensor data, enabling or disabling a sensor, setting the sensor data reporting mode,
 * and setting sensor options such as the accuracy and measurement range.
 *
 * @since 6.1
 * @version 1.0
 */

package ohos.hdi.sensor.convert.v1_0;

import ohos.hdi.sensor.convert.v1_0.ISensorConvertTypes;

/**
 * @brief Defines the functions for performing basic operations on sensors.
 *
 * The operations include obtaining sensor information, subscribing to or unsubscribing from sensor data,
 * enabling or disabling a sensor, setting the sensor data reporting mode, and setting sensor options such as
 * the accuracy and measurement range.
 */

interface ISensorConvertInterfaces {
    /**
     * @brief used for converting sensor data
     *
     * @param status Indicates the conversion policy. For details, see {@link HdfDeviceStatusPolicy}.
     * @param inSensorData Indicates the sensor data that needs to be converted. For details, see {@link HdfSensorData}.
     * @param outSensorData Indicates the converted sensor data. For details, see {@link HdfSensorData}.
     * @return Returns <b>0</b> if the sensor is successfully converted; returns a negative value otherwise.
     *
     * @since 6.1
     * @version 1.0
     */
    ConvertSensorData([in] struct HdfDeviceStatusPolicy status, [in] struct HdfSensorData inSensorData,
        [out] struct HdfSensorData outSensorData);
}
