/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.display.composer.v1_1;

import ohos.hdi.display.composer.v1_1.DisplayComposerType;

[callback] interface IModeCallback {
    /**
     * @brief the callback to be invoked when display mode changes.
     *
     * @param modeId display mode id returned by {@link GetDisplaySupportedModes}
     * @param vBlankPeriod the vblank period indicated by modeId
     *
     * @return Returns <b>0</b> if the operation is successful; returns an error code defined
     * in {@link DispErrCode} otherwise.
     * @since 4.1
     * @version 1.1
     */
    OnMode([in] unsigned int modeId, [in] unsigned long vBlankPeriod);
}