/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.vibrator.v1_1;

/**
 * @brief Enumerates the vibration modes of this vibrator.
 *
 * @since 2.2
 */
enum HdfVibratorMode {
    /**< Indicates the one-shot vibration with the given duration. */
    HDF_VIBRATOR_MODE_ONCE,
    /**< Indicates the periodic vibration with the preset effect. */
    HDF_VIBRATOR_MODE_PRESET,
    /**< Indicates invalid the effect mode. */
    HDF_VIBRATOR_MODE_BUTT,
};

/**
 * @brief Defines the vibration parameters.
 *
 * The parameters include the setting intensity and frequency capability the on and intensity and frequency range.
 *
 * @since 3.2
 */
struct HdfVibratorInfo {
    /**< setting intensity capability. 1 indicates support, 0 indicates not support. */
    int isSupportIntensity;
    /**< setting frequency capability. 1 indicates support, 0 indicates not support. */
    int isSupportFrequency;
    /**< Max intensity */
    int intensityMaxValue;
    /**< Min intensity */
    int intensityMinValue;
    /**< Max frequency */
    int frequencyMaxValue;
    /**< Min frequency */
    int frequencyMinValue;
};
