/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.ril.v1_0;

import ohos.hdi.ril.v1_0.Types;

[callback] interface IRilCallback {
    CallEmergencyNotice([in] struct RilRadioResponseInfo responseInfo,
        [in] struct EmergencyInfoList emergencyInfoList);
    CallStateUpdated([in] struct RilRadioResponseInfo responseInfo);
    CallRingbackVoiceNotice([in] struct RilRadioResponseInfo responseInfo,
        [in] struct RingbackVoice ringbackVoice);
    CallSrvccStatusNotice([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SrvccStatus srvccStatus);
    CallRsrvccStatusNotify([in] struct RilRadioResponseInfo responseInfo);
    CallUssdNotice([in] struct RilRadioResponseInfo responseInfo,
        [in] struct UssdNoticeInfo ussdNoticeInfo);
    CallSsNotice([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SsNoticeInfo ssNoticeInfo);
    SetEmergencyCallListResponse([in] struct RilRadioResponseInfo responseInfo);
    GetEmergencyCallListResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct EmergencyInfoList emergencyInfoList);
    GetCallListResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CallInfoList callList);
    DialResponse([in] struct RilRadioResponseInfo responseInfo);
    HangupResponse([in] struct RilRadioResponseInfo responseInfo);
    RejectResponse([in] struct RilRadioResponseInfo responseInfo);
    AnswerResponse([in] struct RilRadioResponseInfo responseInfo);
    HoldCallResponse([in] struct RilRadioResponseInfo responseInfo);
    UnHoldCallResponse([in] struct RilRadioResponseInfo responseInfo);
    SwitchCallResponse([in] struct RilRadioResponseInfo responseInfo);
    GetClipResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct GetClipResult getClipResult);
    SetClipResponse([in] struct RilRadioResponseInfo responseInfo);
    CombineConferenceResponse([in] struct RilRadioResponseInfo responseInfo);
    SeparateConferenceResponse([in] struct RilRadioResponseInfo responseInfo);
    CallSupplementResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCallWaitingResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CallWaitResult callWaitResult);
    SetCallWaitingResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCallTransferInfoResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CallForwardQueryInfoList cFQueryList);
    SetCallTransferInfoResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCallRestrictionResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CallRestrictionResult result);
    SetCallRestrictionResponse([in] struct RilRadioResponseInfo responseInfo);
    GetClirResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct GetClirResult getClirResult);
    SetClirResponse([in] struct RilRadioResponseInfo responseInfo);
    StartDtmfResponse([in] struct RilRadioResponseInfo responseInfo);
    SendDtmfResponse([in] struct RilRadioResponseInfo responseInfo);
    StopDtmfResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCallPreferenceModeResponse([in] struct RilRadioResponseInfo responseInfo, [in] int mode);
    SetCallPreferenceModeResponse([in] struct RilRadioResponseInfo responseInfo);
    SetUssdResponse([in] struct RilRadioResponseInfo responseInfo);
    GetUssdResponse([in] struct RilRadioResponseInfo responseInfo, [in] int cusd);
    SetMuteResponse([in] struct RilRadioResponseInfo responseInfo);
    GetMuteResponse([in] struct RilRadioResponseInfo responseInfo, [in] int mute);
    GetCallFailReasonResponse([in] struct RilRadioResponseInfo responseInfo, [in] int callFail);
    SetBarringPasswordResponse([in] struct RilRadioResponseInfo responseInfo);

    PdpContextListUpdated([in] struct RilRadioResponseInfo responseInfo, [in] struct DataCallResultList dataCallResultList);
    ActivatePdpContextResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SetupDataCallResultInfo setupDataCallResultInfo);
    DeactivatePdpContextResponse([in] struct RilRadioResponseInfo responseInfo);
    GetPdpContextListResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct DataCallResultList dataCallResultList);
    SetInitApnInfoResponse([in] struct RilRadioResponseInfo responseInfo);
    GetLinkBandwidthInfoResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct DataLinkBandwidthInfo dataLinkBandwidthInfo);
    SetLinkBandwidthReportingRuleResponse([in] struct RilRadioResponseInfo responseInfo);
    SetDataPermittedResponse([in] struct RilRadioResponseInfo responseInfo);

    RadioStateUpdated([in] struct RilRadioResponseInfo responseInfo, [in] int state);
    VoiceRadioTechUpdated([in] struct RilRadioResponseInfo responseInfo,
        [in] struct VoiceRadioTechnology voiceRadioTechnology);
    ShutDownResponse([in] struct RilRadioResponseInfo responseInfo);
    SetRadioStateResponse([in] struct RilRadioResponseInfo responseInfo);
    GetRadioStateResponse([in] struct RilRadioResponseInfo responseInfo,[in] int state);
    GetImeiResponse([in] struct RilRadioResponseInfo responseInfo, [in] String imei);
    GetMeidResponse([in] struct RilRadioResponseInfo responseInfo, [in] String meid);
    GetVoiceRadioTechnologyResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct VoiceRadioTechnology voiceRadioTechnology);
    GetBasebandVersionResponse([in] struct RilRadioResponseInfo responseInfo, [in] String basebandVersion);

    SimStateUpdated([in] struct RilRadioResponseInfo responseInfo);
    SimStkSessionEndNotify([in] struct RilRadioResponseInfo responseInfo);
    SimStkProactiveNotify([in] struct RilRadioResponseInfo responseInfo, [in] String response);
    SimStkAlphaNotify([in] struct RilRadioResponseInfo responseInfo, [in] String response);
    SimStkEventNotify([in] struct RilRadioResponseInfo responseInfo, [in] String response);
    SimStkCallSetupNotify([in] struct RilRadioResponseInfo responseInfo);
    SimRefreshNotify([in] struct RilRadioResponseInfo responseInfo);
    SimRadioProtocolUpdated([in] struct RilRadioResponseInfo responseInfo, [in] struct RadioProtocol radioProtocol);
    GetSimIOResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct IccIoResultInfo result);
    GetSimStatusResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct CardStatusInfo result);
    GetImsiResponse([in] struct RilRadioResponseInfo responseInfo, [in] String response);
    GetSimLockStatusResponse([in] struct RilRadioResponseInfo responseInfo, [in] int simLockStatus);
    SetSimLockResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    ChangeSimPasswordResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    UnlockPinResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    UnlockPukResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    UnlockPin2Response([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    UnlockPuk2Response([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);
    SetActiveSimResponse([in] struct RilRadioResponseInfo responseInfo);
    SimStkSendTerminalResponseResponse([in] struct RilRadioResponseInfo responseInfo);
    SimStkSendEnvelopeResponse([in] struct RilRadioResponseInfo responseInfo);
    SimStkSendCallSetupRequestResultResponse([in] struct RilRadioResponseInfo responseInfo);
    SimStkIsReadyResponse([in] struct RilRadioResponseInfo responseInfo);
    GetRadioProtocolResponse([in] struct RilRadioResponseInfo responseInfo,[in] struct RadioProtocol radioProtocol);
    SetRadioProtocolResponse([in] struct RilRadioResponseInfo responseInfo,[in] struct RadioProtocol radioProtocol);
    SimOpenLogicalChannelResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct OpenLogicalChannelResponse pOpenLogicalChannelResponse);
    SimCloseLogicalChannelResponse([in] struct RilRadioResponseInfo responseInfo);
    SimTransmitApduLogicalChannelResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct IccIoResultInfo result);
    SimTransmitApduBasicChannelResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct IccIoResultInfo result);
    SimAuthenticationResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct IccIoResultInfo result);
    UnlockSimLockResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct LockStatusResp lockStatus);

    NetworkCsRegStatusUpdated([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CsRegStatusInfo csRegStatusInfo);
    NetworkPsRegStatusUpdated([in] struct RilRadioResponseInfo responseInfo,
        [in] struct PsRegStatusInfo psRegStatusInfo);
    SignalStrengthUpdated([in] struct RilRadioResponseInfo responseInfo, [in] struct Rssi rssi);
    NetworkTimeZoneUpdated([in] struct RilRadioResponseInfo responseInfo, [in] String timeZoneStr);
    NetworkTimeUpdated([in] struct RilRadioResponseInfo responseInfo, [in] String timeStr);
    NetworkPhyChnlCfgUpdated([in] struct RilRadioResponseInfo responseInfo,
        [in] struct ChannelConfigInfoList channelConfigInfoList);
    NetworkCurrentCellUpdated([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CellListCurrentInfo cellListCurrentInfo);
    GetSignalStrengthResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct Rssi rssi);
    GetCsRegStatusResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CsRegStatusInfo csRegStatusInfo);
    GetPsRegStatusResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct PsRegStatusInfo psRegStatusInfo);
    GetOperatorInfoResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct OperatorInfo psRegStatusInfo);
    GetNetworkSearchInformationResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct AvailableNetworkList availableNetworkList);
    GetNetworkSelectionModeResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SetNetworkModeInfo setNetworkModeInfo);
    SetNetworkSelectionModeResponse([in] struct RilRadioResponseInfo responseInfo);
    GetNeighboringCellInfoListResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CellListNearbyInfo cellListNearbyInfo);
    GetCurrentCellInfoResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CellListCurrentInfo cellListCurrentInfo);
    SetPreferredNetworkResponse([in] struct RilRadioResponseInfo responseInfo);
    GetPreferredNetworkResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct PreferredNetworkTypeInfo preferredNetworkTypeInfo);
    GetPhysicalChannelConfigResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct ChannelConfigInfoList channelConfigInfoList);
    SetLocateUpdatesResponse([in] struct RilRadioResponseInfo responseInfo);
    SetNotificationFilterResponse([in] struct RilRadioResponseInfo responseInfo);
    SetDeviceStateResponse([in] struct RilRadioResponseInfo responseInfo);

    NewSmsNotify([in] struct RilRadioResponseInfo responseInfo, [in] struct SmsMessageInfo smsMessageInfo);
    NewCdmaSmsNotify([in] struct RilRadioResponseInfo responseInfo, [in] struct SmsMessageInfo smsMessageInfo);
    SmsStatusReportNotify([in] struct RilRadioResponseInfo responseInfo, [in] struct SmsMessageInfo smsMessageInfo);
    NewSmsStoredOnSimNotify([in] struct RilRadioResponseInfo responseInfo, [in] int recordNumber,
        [in] int indicationType);
    CBConfigNotify([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CBConfigReportInfo cellBroadConfigReportInfo);
    SendGsmSmsResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct SendSmsResultInfo sendSmsResultInfo);
    SendCdmaSmsResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SendSmsResultInfo sendSmsResultInfo);
    AddSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    DelSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    UpdateSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    AddCdmaSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    DelCdmaSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    UpdateCdmaSimMessageResponse([in] struct RilRadioResponseInfo responseInfo);
    SetSmscAddrResponse([in] struct RilRadioResponseInfo responseInfo);
    GetSmscAddrResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct ServiceCenterAddress serviceCenterAddress);
    SetCBConfigResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCBConfigResponse([in] struct RilRadioResponseInfo responseInfo, [in] struct CBConfigInfo cellBroadcastInfo);
    SetCdmaCBConfigResponse([in] struct RilRadioResponseInfo responseInfo);
    GetCdmaCBConfigResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct CdmaCBConfigInfo cdmaCBConfigInfo);
    SendSmsMoreModeResponse([in] struct RilRadioResponseInfo responseInfo,
        [in] struct SendSmsResultInfo sendSmsResultInfo);
    SendSmsAckResponse([in] struct RilRadioResponseInfo responseInfo);

    CommonErrorResponse([in] struct RilRadioResponseInfo responseInfo);
}
