/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.ril.v1_0;

enum IEccType {
    TYPE_CATEGORY = 0,
    TYPE_POLICE = 1,
    TYPE_AMBULANCE = 2,
    TYPE_FIRE = 4,
    TYPE_SEA = 8,
    TYPE_MOUNTAIN = 16,
};
enum ISimpresentType {
    TYPE_NO_CARD = 0,
    TYPE_HAS_CARD = 1,
};
enum IAbnormalServiceType {
    TYPE_ALL = 0,
    TYPE_ONLY_CS = 1,
};
enum IHRilErrType {
    NONE = 0,
    HRIL_ERR_GENERIC_FAILURE = 1,
    HRIL_ERR_INVALID_PARAMETER = 2,
    HRIL_ERR_MEMORY_FULL = 3,
    HRIL_ERR_CMD_SEND_FAILURE = 4,
    HRIL_ERR_CMD_NO_CARRIER = 5,
    HRIL_ERR_INVALID_RESPONSE = 6,
    HRIL_ERR_REPEAT_STATUS = 7,
    HRIL_ERR_NETWORK_SEARCHING = 8,
    HRIL_ERR_NETWORK_SEARCHING_INTERRUPTED = 9,
    HRIL_ERR_MODEM_DEVICE_CLOSE = 10,
    HRIL_ERR_NO_SIMCARD_INSERTED = 11,
    HRIL_ERR_NEED_PIN_CODE = 12,
    HRIL_ERR_NEED_PUK_CODE = 13,
    HRIL_ERR_NETWORK_SEARCH_TIMEOUT = 14,
    HRIL_ERR_PINPUK_PASSWORD_NOCORRECT = 15,
    HRIL_ERR_INVALID_MODEM_PARAMETER = 50,
    HRIL_ERR_HDF_IPC_FAILURE = 65535,
    HRIL_ERR_NULL_POINT = 65536,
};
enum IHRilResponseTypes {
    HRIL_RESPONSE_REQUEST = 0,
    HRIL_RESPONSE_NOTICE = 1,
    HRIL_RESPONSE_REQUEST_ACK = 2,
    HRIL_RESPONSE_REQUEST_MUST_ACK = 3,
    HRIL_RESPONSE_NOTICE_MUST_ACK = 4,
};
enum IHRilSrvStatus {
  HRIL_NO_SRV_SERVICE = 0,
  HRIL_RESTRICTED_SERVICE = 1,
  HRIL_SERVICE_VALID = 2,
  HRIL_REGIONAL_SERVICE = 3,
  HRIL_ENERGY_SAVING_SERVICE = 4,
};
enum IHRilSrvDomain {
  HRIL_NO_DOMAIN_SERVICE = 0,
  HRIL_CS_SERVICE = 1,
  HRIL_PS_SERVICE = 2,
  HRIL_CS_PS_SERVICE = 3,
  HRIL_CS_PS_SEARCHING = 4,
  HRIL_CDMA_NOT_SUPPORT = 255,
};
enum IHRilRoamStatus {
  HRIL_NO_ROAM = 0,
  HRIL_ROAMING = 1,
  HRIL_ROAM_UNKNOWN = 2,
};
enum IHRilSimLockStatus {
  HRIL_SIM_CARD_UNLOCK = 0,
  HRIL_SIM_CARD_LOCK = 1,
};
enum IHRilSysMode {
  HRIL_NO_SYSMODE_SERVICE = 0,
  HRIL_GSM_MODE = 1,
  HRIL_CDMA_MODE = 2,
  HRIL_WCDMA_MODE = 3,
  HRIL_TDSCDMA_MODE = 4,
  HRIL_WIMAX_MODE = 5,
  HRIL_LTE_MODE = 6,
  HRIL_LTE_CA_MODE = 7,
  HRIL_NR_MODE = 8,
};
enum IHRilRadioTech {
  RADIO_TECHNOLOGY_INVALID = 65535,
  RADIO_TECHNOLOGY_UNKNOWN = 0,
  RADIO_TECHNOLOGY_GSM = 1,
  RADIO_TECHNOLOGY_1XRTT = 2,
  RADIO_TECHNOLOGY_WCDMA = 3,
  RADIO_TECHNOLOGY_HSPA = 4,
  RADIO_TECHNOLOGY_HSPAP = 5,
  RADIO_TECHNOLOGY_TD_SCDMA = 6,
  RADIO_TECHNOLOGY_EVDO = 7,
  RADIO_TECHNOLOGY_EHRPD = 8,
  RADIO_TECHNOLOGY_LTE = 9,
  RADIO_TECHNOLOGY_LTE_CA = 10,
  RADIO_TECHNOLOGY_IWLAN = 11,
  RADIO_TECHNOLOGY_NR = 12,
};
enum IHRilSimStatus {
  HRIL_USIM_INVALID = 0,
  HRIL_USIM_VALID = 1,
  HRIL_USIM_CS_INVALID = 2,
  HRIL_USIM_PS_INVALID = 3,
  HRIL_USIM_CS_PS_INVALID = 4,
  HRIL_ROM_SIM = 240,
  HRIL_NO_USIM = 255,
};
enum IHRilRegStatus {
    NO_REG_MT_NO_SEARCH = 0,
    REG_MT_HOME = 1,
    NO_REG_MT_SEARCHING = 2,
    REG_MT_REJECTED = 3,
    REG_MT_UNKNOWN = 4,
    REG_MT_ROAMING = 5,
    REG_MT_EMERGENCY = 6,
};
enum IHRilCellConnectionStatus {
    HRIL_SERVING_CELL_UNKNOWN = 0,
    HRIL_SERVING_CELL_PRIMARY = 1,
    HRIL_SERVING_CELL_SECONDARY = 2,
};
enum IHRilRegNotifyMode {
    REG_NOT_NOTIFY = 0,
    REG_NOTIFY_STAT_ONLY = 1,
    REG_NOTIFY_STAT_LAC_CELLID = 2,
};
enum IRadioProtocolPhase {
    RADIO_PROTOCOL_PHASE_INITIAL,
    RADIO_PROTOCOL_PHASE_CHECK,
    RADIO_PROTOCOL_PHASE_UPDATE,
    RADIO_PROTOCOL_PHASE_NOTIFY,
    RADIO_PROTOCOL_PHASE_COMPLETE,
};
enum IRadioProtocolStatus {
    RADIO_PROTOCOL_STATUS_NONE,
    RADIO_PROTOCOL_STATUS_SUCCESS,
    RADIO_PROTOCOL_STATUS_FAIL,
};
struct IEmergencyCall {
    int index;
    int total;
    String eccNum;
    String mcc;
    enum IEccType eccType;
    enum ISimpresentType simpresent;
    enum IAbnormalServiceType abnormalService;
};
struct IEmergencyInfoList {
    int callSize;
    int flag;
    List<struct IEmergencyCall> calls;
};
struct IHRilRadioResponseInfo {
    int slotId;
    int flag;
    int serial;
    enum IHRilErrType error;
    enum IHRilResponseTypes type;
};
struct ISetupDataCallResultInfo {
    int flag;
    int reason;
    int retryTime;
    int cid;
    int active;
    String type;
    String netPortName;
    String address;
    String dns;
    String dnsSec;
    String gateway;
    int maxTransferUnit;
    String pCscfPrimAddr;
    String pCscfSecAddr;
    int pduSessionId;
};
struct IDataCallResultList {
    int size;
    List<struct ISetupDataCallResultInfo> dcList;
};
struct IDataProfileDataInfo {
    int serial;
    int profileId;
    String apn;
    String protocol;
    String roamingProtocol;
    int verType;
    String userName;
    String password;
};
struct IDataProfilesInfo {
    int serial;
    int profilesSize;
    List<struct IDataProfileDataInfo> profiles;
    boolean isRoaming;
};
struct IDataCallInfo {
    int serial;
    int radioTechnology;
    struct IDataProfileDataInfo dataProfileInfo;
    boolean modemCognitive;
    boolean roamingAllowed;
    boolean isRoaming;
};
struct IDataLinkBandwidthInfo {
    int serial;
    int cid;
    int qi;
    int dlGfbr;
    int ulGfbr;
    int dlMfbr;
    int ulMfbr;
    int ulSambr;
    int dlSambr;
    int averagingWindow;
};
struct IDataLinkBandwidthReportingRule {
    int serial;
    int rat;
    int delayMs;
    int delayUplinkKbps;
    int delayDownlinkKbps;
    int maximumUplinkKbpsSize;
    int maximumDownlinkKbpsSize;
    List<int> maximumUplinkKbps;
    List<int> maximumDownlinkKbps;
};
struct IUniInfo {
    int serial;
    int gsmIndex;
    boolean flag;
    int arg1;
    int arg2;
    String strTmp;
};
struct IVoiceRadioTechnology {
  enum IHRilSrvStatus srvStatus;
  enum IHRilSrvDomain srvDomain;
  enum IHRilRoamStatus roamStatus;
  enum IHRilSimStatus simStatus;
  enum IHRilSimLockStatus lockStatus;
  enum IHRilSysMode sysMode;
  String sysModeName;
  enum IHRilRadioTech actType;
  String actName;
  int flag;
};
struct IDialInfo {
    int serial;
    String address;
    int clir;
};
struct ICallInfo {
    int index;
    int dir;
    int state;
    int mode;
    int mpty;
    int voiceDomain;
    int callType;
    String number;
    int type;
    String alpha;
};
struct ICallInfoList {
    int callSize;
    int flag;
    List<struct ICallInfo> calls;
};
struct IGetClipResult {
    int result;
    int action;
    int clipStat;
};
struct IGetClirResult {
    int result;
    int action;
    int clirStat;
};
struct ICallWaitResult {
    int result;
    int status;
    int classCw;
};
struct ICallRestrictionInfo {
    String fac;
    int mode;
    String password;
};
struct ICallRestrictionResult {
    int result;
    int status;
    int classCw;
};
struct ICallForwardSetInfo {
    int reason;
    int mode;
    String number;
    int classx;
};
struct ICallForwardQueryResult {
    int serial;
    int result;
    int status;
    int classx;
    String number;
    int type;
    int reason;
    int time;
};
struct ICallForwardQueryInfoList {
    int callSize;
    int flag;
    List<struct ICallForwardQueryResult> calls;
};
struct IUssdNoticeInfo {
    int m;
    String str;
};
struct ISsNoticeInfo {
    int serviceType;
    int requestType;
    int serviceClass;
    int result;
};
struct ISrvccStatus {
    int status;
};
struct IRingbackVoice {
    int status;
};
struct IDtmfInfo {
    int callId;
    String dtmfKey;
    int onLength;
    int offLength;
    int stringLength;
};
struct ISetBarringInfo {
    String fac;
    String oldPassword;
    String newPassword;
};
struct ICardStatusInfo {
    int index;
    int simType;
    int simState;
};
struct ISimIoRequestInfo {
    int command;
    int fileId;
    int p1;
    int p2;
    int p3;
    String data;
    String path;
    int serial;
    String pin2;
    String aid;
};
struct IIccIoResultInfo {
    int sw1;
    int sw2;
    String response;
};
struct ISimLockInfo {
    int serial;
    String fac;
    int mode;
    int status;
    String passwd;
    int classx;
};
struct ISimPasswordInfo {
    int serial;
    String fac;
    String oldPassword;
    String newPassword;
    int passwordLength;
};
struct ISimPinInputTimes {
    int serial;
    String code;
    int times;
    int pukTimes;
    int pinTimes;
    int puk2Times;
    int pin2Times;
};
struct IApduSimIORequestInfo {
    int serial;
    int channelId;
    int type;
    int instruction;
    int p1;
    int p2;
    int p3;
    String data;
};
struct ISimAuthenticationRequestInfo {
    int serial;
    String aid;
    String authData;
};
struct IOpenLogicalChannelResponse {
    int sw1;
    int sw2;
    int channelId;
    String response;
};
struct ILockStatusResp {
    int result;
    int remain;
};
struct IRadioProtocol {
    int slotId;
    int sessionId;
    int technology;
    int modemId;
    enum IRadioProtocolPhase phase;
    enum IRadioProtocolStatus status;
};
struct IGsmRssi {
    int rxlev;
    int ber;
};
struct ICdmaRssi {
    int absoluteRssi;
    int ecno;
};
struct IWcdmaRssi {
    int rxlev;
    int ecio;
    int rscp;
    int ber;
};
struct ILteRssi {
    int rxlev;
    int rsrq;
    int rsrp;
    int snr;
};
struct ITdScdmaRssi {
    int rscp;
};
struct INrRssi {
    int rsrp;
    int rsrq;
    int sinr;
};
struct IRssi {
    struct IGsmRssi gw;
    struct ICdmaRssi cdma;
    struct IWcdmaRssi wcdma;
    struct ILteRssi lte;
    struct ITdScdmaRssi tdScdma;
    struct INrRssi nr;
};
struct ICsRegStatusInfo {
    int notifyType;
    enum IHRilRegStatus regStatus;
    int lacCode;
    int cellId;
    enum IHRilRadioTech radioTechnology;
    int flag;
};
struct IPsRegStatusInfo {
    int notifyType;
    enum IHRilRegStatus regStatus;
    int lacCode;
    int cellId;
    enum IHRilRadioTech radioTechnology;
    boolean isNrAvailable;
    boolean isEnDcAvailable;
    boolean isDcNrRestricted;
};
struct IOperatorInfo {
    String longName;
    String shortName;
    String numeric;
};
struct IAvailableNetworkInfo {
    String longName;
    String shortName;
    String numeric;
    int status;
    int rat;
};
struct IAvailableNetworkList {
    int itemNum;
    List<struct IAvailableNetworkInfo> availableNetworkInfo;
    int flag;
};
struct ISetNetworkModeInfo {
    int selectMode;
    String oper;
    int flag;
};
struct ICellListRatGsm {
    int band;
    int arfcn;
    int bsic;
    int cellId;
    int lac;
    int rxlev;
};
struct ICellListRatLte {
    int arfcn;
    int pci;
    int rsrp;
    int rsrq;
    int rxlev;
};
struct ICellListRatWcdma {
    int arfcn;
    int psc;
    int rscp;
    int ecno;
};
struct ICellListRatCdma {
    int systemId;
    int networkId;
    int baseId;
    int zoneId;
    int pilotPn;
    int pilotStrength;
    int channel;
    int longitude;
    int latitude;
};
struct ICellListRatTdscdma {
    int arfcn;
    int syncId;
    int sc;
    int cellId;
    int lac;
    int rscp;
    int drx;
    int rac;
    int cpid;
};
struct ICellListRatNr {
    int nrArfcn;
    int pci;
    int tac;
    int nci;
};
union IServiceCellParas {
    struct ICellListRatGsm gsm;
    struct ICellListRatLte lte;
    struct ICellListRatWcdma wcdma;
    struct ICellListRatCdma cdma;
    struct ICellListRatTdscdma tdscdma;
    struct ICellListRatNr nr;
};
struct ICellNearbyInfo {
    int ratType;
    union IServiceCellParas serviceCells;
};
struct ICellListNearbyInfo {
    int itemNum;
    List<struct ICellNearbyInfo> cellNearbyInfo;
};
struct ICellRatGsm {
    int band;
    int arfcn;
    int bsic;
    int cellId;
    int lac;
    int rxlev;
    int rxQuality;
    int ta;
};
struct ICellRatLte {
    int arfcn;
    int cellId;
    int pci;
    int tac;
    int rsrp;
    int rsrq;
    int rssi;
};
struct ICellRatWcdma {
    int arfcn;
    int psc;
    int cellId;
    int lac;
    int rscp;
    int rxlev;
    int ecno;
    int drx;
    int ura;
};
struct ICellRatCdma {
    int systemId;
    int networkId;
    int baseId;
    int zoneId;
    int pilotPn;
    int pilotStrength;
    int channel;
    int longitude;
    int latitude;
};
struct ICellRatTdscdma {
    int arfcn;
    int syncId;
    int sc;
    int cellId;
    int lac;
    int rscp;
    int drx;
    int rac;
    int cpid;
};
struct ICellRatNr {
    int nrArfcn;
    int pci;
    int tac;
    int nci;
};
union ICurrentServiceCellParas {
    struct ICellRatGsm gsm;
    struct ICellRatLte lte;
    struct ICellRatWcdma wcdma;
    struct ICellRatCdma cdma;
    struct ICellRatTdscdma tdscdma;
    struct ICellRatNr nr;
};
struct ICurrentCellInfo {
    int ratType;
    int mcc;
    int mnc;
    union ICurrentServiceCellParas serviceCells;
};
struct ICellListCurrentInfo {
    int itemNum;
    List<struct ICurrentCellInfo> cellCurrentInfo;
};
struct IPreferredNetworkTypeInfo {
    int preferredNetworkType;
    int flag;
};
struct IPhysicalChannelConfig {
    enum IHRilCellConnectionStatus cellConnStatus;
    enum IHRilRadioTech ratType;
    int cellBandwidthDownlinkKhz;
    int cellBandwidthUplinkKhz;
    int freqRange;
    int downlinkChannelNum;
    int uplinkChannelNum;
    int physicalCellId;
    int contextIdNum;
    List<int> contextIds;
};
struct IChannelConfigInfoList {
    int itemNum;
    List<struct IPhysicalChannelConfig> channelConfigInfos;
    int flag;
};
struct IGsmSmsMessageInfo {
    int serial;
    String smscPdu;
    String pdu;
    int state;
};
struct ISendCdmaSmsMessageInfo {
    int serial;
    String smscPdu;
    int state;
};
struct ISmsMessageIOInfo {
    int serial;
    String smscPdu;
    String pdu;
    int state;
    int index;
};
struct IServiceCenterAddress {
    int serial;
    int tosca;
    String address;
};
struct ICBConfigInfo {
    int serial;
    int mode;
    int indicationType;
    String mids;
    String dcss;
};
struct ICdmaCBConfigInfo {
    int service;
    int language;
    int checked;
};
struct ICdmaCBConfigInfoList {
    int serial;
    int size;
    List<struct ICdmaCBConfigInfo> list;
};
struct ICBConfigReportInfo {
    int indicationType;
    int sn;
    int mid;
    int page;
    int pages;
    String dcs;
    String data;
    int length;
    String pdu;
};
struct ISmsMessageInfo {
    int indicationType;
    int size;
    List<unsigned char> pdu;
};
struct IModeData {
    int serial;
    boolean result;
    int mode;
    String pdu;
};
struct ISendSmsResultInfo {
    int msgRef;
    String pdu;
    int errCode;
    int flag;
};