/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.intelligent_voice.engine.v1_0;

enum IntellVoiceEngineAdapterType {
    ENROLL_ADAPTER_TYPE = 0,
    WAKEUP_ADAPTER_TYPE = 1,
    UPDATE_ADAPTER_TYPE = 2,
    ADAPTER_TYPE_BUT,
};

enum ContentType {
    DSP_MODLE = 0,
    CONTENT_TYPE_BUT,
};

enum IntellVoiceEngineMessageType {
    INTELL_VOICE_ENGINE_MSG_NONE = 0,
    INTELL_VOICE_ENGINE_MSG_INIT_DONE = 1,
    INTELL_VOICE_ENGINE_MSG_ENROLL_COMPLETE = 2,
    INTELL_VOICE_ENGINE_MSG_COMMIT_ENROLL_COMPLETE = 3,
    INTELL_VOICE_ENGINE_MSG_RECOGNIZE_COMPLETE = 4,
};

enum IntellVoiceEngineErrors {
    INTELL_VOICE_ENGINE_OK = 0,

    INTELL_VOICE_ENGINE_ERROR_OFFSET = -100,
    INTELL_VOICE_ENGINE_INVALID_PARAMS = -101,
    INTELL_VOICE_ENGINE_INIT_FAILED = -102,
    INTELL_VOICE_ENGINE_ENROLL_FAILED = -103,
    INTELL_VOICE_ENGINE_COMMIT_ENROLL_FAILED = -104,
    INTELL_VOICE_ENGINE_WAKEUP_FAILED = -105,
};

struct IntellVoiceEngineAdapterDescriptor {
    enum IntellVoiceEngineAdapterType adapterType;
};

struct IntellVoiceEngineAdapterInfo {
    String wakeupPhrase;
    int minBufSize;
    int sampleChannels;
    int bitsPerSample;
    int sampleRate;
};

struct StartInfo {
    boolean isLast;
};

struct IntellVoiceEngineCallBackEvent {
    enum IntellVoiceEngineMessageType msgId;
    enum IntellVoiceEngineErrors result;
    String info;
};