/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 /**
 * @addtogroup HdiDrm
 * @
 * @brief Defines APIs of the Drm module.
 * The Drm module provides APIs for multimedia Drm.
 * @since 6.1
 * @version 1.1
 */

/**
 * @file MediaKeySystemTypes.idl
 *
 * @brief Defines the types used in HdiDrm.
 * @since 6.1
 * @version 1.1
 */


 package ohos.hdi.drm.v1_1;
 import ohos.hdi.drm.v1_0.MediaKeySystemTypes;


/**
 * @brief Defines DRM error code type.
 *
 * @since 6.1
 * @version 1.1
 */
enum DrmErrorCode {
    DRM_ERROR_OK = 0,
    DRM_ERROR_START = 0xfffff000,
    DRM_ERROR_UNKNOWN,
    DRM_ERROR_OPERATION_NOT_PERMITTED,
    DRM_ERROR_MAX_SYSTEM_NUM_REACHED,
    DRM_ERROR_MAX_SESSION_NUM_REACHED,
    DRM_ERROR_NO_MEMORY,
    DRM_ERROR_INVALID_VAL,
    DRM_ERROR_IO,
    DRM_ERROR_TIMEOUT,
    DRM_ERROR_SERVICE_DIED,
    DRM_ERROR_INVALID_STATE,
    DRM_ERROR_UNSUPPORTED,
    DRM_ERROR_INVALID_KEY_SESSION,
    DRM_ERROR_INVALID_MEDIA_KEY_SYSTEM,
    DRM_ERROR_CRYPTO_ERROR,
    DRM_ERROR_NOT_PROVISIONED,
    DRM_ERROR_DEVICE_TIME_ERROR,
    DRM_ERROR_PROVISIONING_NOT_ALLOWED,
    DRM_ERROR_PROVISIONING_NO_DEVICE_CERT,
    DRM_ERROR_PROVISIONING_INVALID_SERVER_CERTIFICATES,
    DRM_ERROR_PROVISIONING_SERVER_CERTIFICATES_EXPIRED,
    DRM_ERROR_PROVISIONING_INVALID_MESSAGE,
    DRM_ERROR_PROVISIONING_INVALID_DRM_CERTIFICATES,
    DRM_ERROR_PROVISIONING_TIME_ERROR,
    DRM_ERROR_STORAGE_READ,
    DRM_ERROR_STORAGE_WRITE,
    DRM_ERROR_KEY_REQUEST_NOT_ALLOWED,
    DRM_ERROR_KEY_REQUEST_INVALID_MEDIA_KEY_TYPE,
    DRM_ERROR_KEY_REQUEST_INVALID_MIMETYPE,
    DRM_ERROR_KEY_REQUEST_INVALID_INITDATA,
    DRM_ERROR_KEY_REQUEST_INVALID_DRM_CERTIFICATES,
    DRM_ERROR_KEY_REQUEST_DRM_CERTIFICATES_EXPIRED,
    DRM_ERROR_KEY_REQUEST_DRM_CERTIFICATES_REVOKED,
    DRM_ERROR_KEY_RESPONSE_INVALID_MESSAGE,
    DRM_ERROR_KEY_RESPONSE_INVALID_SERVER_CERTIFICATES,
    DRM_ERROR_KEY_RESPONSE_SERVER_CERTIFICATES_EXPIRED,
    DRM_ERROR_KEY_RESPONSE_TIME_ERROR,
    DRM_ERROR_KEY_RESPONSE_DENIED,
    DRM_ERROR_KEY_RESTORE_INVALID_MEDIA_KEY_ID,
    DRM_ERROR_DECRYPT_ALGORITHM_NOT_SUPPORT,
    DRM_ERROR_DECRYPT_NO_LICENSE,
    DRM_ERROR_DECRYPT_NO_KEY,
    DRM_ERROR_DECRYPT_INVALID_IV,
    DRM_ERROR_DECRYPT_INVALID_SUBSAMPLES,
    DRM_ERROR_DECRYPT_INVALID_PATTERN,
    DRM_ERROR_DECRYPT_INVALID_INPUT_BUFFER,
    DRM_ERROR_DECRYPT_INVALID_INPUT_BUFFER_LEN,
    DRM_ERROR_DECRYPT_INVALID_OUTPUT_BUFFER,
    DRM_ERROR_DECRYPT_INVALID_OUTPUT_BUFFER_LEN,
    DRM_ERROR_DECRYPT_SECURE_NOT_SUPPORT,
    DRM_ERROR_POLICY_OUTPUT_PROTECTION_NOT_ALLOWED,
    DRM_ERROR_POLICY_CONTENT_PROTECTION_LEVEL_NOT_ALLOWED,
    DRM_ERROR_POLICY_RENTAL_NOT_ALLOWED,
    DRM_ERROR_POLICY_INVALID_RENEW_PARAMETER,
    DRM_ERROR_POLICY_LICENSE_NEED,
    DRM_ERROR_MEMORY_ERROR,
    DRM_ERROR_TAMPER_FOUND,
    DRM_ERROR_OFFLINE_RESTORE_FAILED,
    DRM_ERROR_DECRYPT_INNER_ERROR,
    DRM_ERROR_SESSION_CALLBACK_INNER_ERROR,
    DRM_ERROR_SYSTEM_CALLBACK_INNER_ERROR,
    DRM_ERROR_GENERATE_MEDIAKEY_REQUEST_INNER_ERROR,
    DRM_ERROR_CHECK_MEDIAKEY_STATUS_INNER_ERROR,
    DRM_ERROR_INVALID_MODULE,
    DRM_ERROR_DESTORY_INNER_ERROR,
    DRM_ERROR_GET_INFO_ERROR,
    DRM_ERROR_SET_CONFIGURATION_STRING_INNER_ERROR,
    DRM_ERROR_SET_CONFIGURATION_BYTE_ARRAY_INNER_ERROR,
    DRM_ERROR_GET_OFFLINE_MEDIA_KEYIDS_INNER_ERROR,
    DRM_ERROR_PROCESS_ONLINE_RESPONSE_INNER_ERROR,
    DRM_ERROR_CLEAR_MEDIA_KEYS_INNER_ERROR,
    DRM_ERROR_CLEAR_OFFLINE_MEDIA_KEYS_INNER_ERROR,
    DRM_ERROR_RESTORE_OFFLINE_MEDIA_KEYS_INNER_ERROR,
    DRM_ERROR_END = 0xffffff00,
};
