/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.display.composer.v1_5;

import ohos.hdi.display.composer.v1_4.IDisplayComposer;
import ohos.hdi.display.composer.v1_0.DisplayComposerType;
import ohos.hdi.display.composer.v1_5.DisplayComposerType;
sequenceable OHOS.HDI.Display.HdifdParcelable;

interface IDisplayComposer extends ohos.hdi.display.composer.v1_4.IDisplayComposer {
    /**
     * @brief Gets the current and maximum values of a VCP code for a physical display device.
     *
     * This interface retrieves the status of a specific Virtual Control Panel (VCP)
     * code for the specified display device, such as brightness or contrast.
     *
     * @param devId Indicates the ID of the display device.
     * @param vcpCode Indicates the VESA VCP code to be queried.
     * @param currentValue Receives the current value of the VCP feature.
     * @param maximumValue Receives the maximum supported value of the VCP feature.
     * @param replyErrorCode Indicates the error code from the underlying DDC/CI protocol,
     * populated only when the function returns 0.
     *
     * @return Returns <b>0</b> if the operation is successful; returns an error code defined
     * in {@link DispErrCode} otherwise.
     * @since 7.0
     * @version 1.0
     */
    GetDisplayVCPFeature([in] unsigned int devId, [in] unsigned char vcpCode,
        [out] unsigned short currentValue, [out] unsigned short maximumValue, [out] int replyErrorCode);
    
    /**
     * @brief Sets the value of a VCP feature for a physical display device.
     *
     * This interface sends a command to adjust a specific Virtual Control Panel (VCP)
     * code for the specified display device, such as setting the brightness level.
     *
     * @param devId Indicates the ID of the display device.
     * @param vcpCode Indicates the VESA VCP code to be set.
     * @param currentValue Indicates the new value to be set for the VCP feature.
     *
     * @return Returns <b>0</b> if the operation is successful; returns an error code defined
     * in {@link DispErrCode} otherwise.
     * @since 7.0
     * @version 1.0
     */
    SetDisplayVCPFeature([in] unsigned int devId, [in] unsigned char vcpCode, [in] unsigned short currentValue);

    /**
     * @brief GetLayerColor.
     *
     * @param devId Indicates the ID of the display device.
     * @param layerId Indicates the ID of the layer.
     * @param color Indicates the solid filled color of the layer.
     *
     * @return Returns <b>0</b> if the operation is successful; returns an error code defined
     * in {@link DispErrCode} otherwise.
     * @since 7.0
     * @version 1.0
     */
    GetLayerColor([in] unsigned int devId, [in] unsigned int layerId, [out] struct LayerColor color);
}
