/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HdfFingerprintAuth
 * @{
 *
 * @brief Provides APIs for the fingerprint auth driver.
 *
 * The fingerprint auth driver provides a unified interface for the fingerprint auth service to access the fingerprint auth driver.
 * After obtaining the fingerprint auth driver proxy, the service can call related APIs to obtain executors.
 * After obtaining the fingerprint auth executors, the service can call related APIs to get executor information, get
 * template information, and enroll, authenticate, and delete templates, etc.
 *
 * @since 3.2
 */

/**
 * @file FingerprintAuthTypes.idl
 *
 * @brief Defines the enumeration and data structure of the fingerprint auth driver, including AuthType, ExecutorRole, ExecutorSecureLevel,
 * DriverCommandId, FaceTipsCode, ExecutorInfo, and TemplateInfo.
 *
 * @since 3.2
 */

package ohos.hdi.fingerprint_auth.v2_0;

/**
 * @brief Enumerates credential types for authentication.
 *
 * @since 3.2
 * @version 1.0
 */
enum AuthType : int {
    /**< Indicates that the authentication type is PIN. */
    PIN = 1,
    /**< Indicates that the authentication type is face. */
    FACE = 2,
    /**< Indicates that the authentication type is fingerprint. */
    FINGERPRINT = 4,
};

/**
 * @brief Enumerates executor roles.
 *
 * @since 3.2
 * @version 2.0
 */
enum ExecutorRole : int {
    /**< Indicates that the executor role is scheduler. */
    SCHEDULER = 0,
    /**< Indicates that the executor role is collector. */
    COLLECTOR = 1,
    /**< Indicates that the executor role is verifier. */
    VERIFIER = 2,
    /**< Indicates that the executor role is the combination of collector and verifier. */
    ALL_IN_ONE = 3,
};

/**
 * @brief Enumerates executor secure levels.
 *
 * @since 3.2
 * @version 1.0
 */
enum ExecutorSecureLevel : int {
    /**< Indicates that the executor secure level is ESL0. */
    ESL0 = 0,
    /**< Indicates that the executor secure level is ESL1. */
    ESL1 = 1,
    /**< Indicates that the executor secure level is ESL2. */
    ESL2 = 2,
    /**< Indicates that the executor secure level is ESL3. */
    ESL3 = 3,
};

/**
 * @brief Enumerates authentication capability levels.
 *
 * @since 5.0
 * @version 1.0
 */
enum AuthenticationCapabilityLevel : int {
    /**< Indicates that the authentication capability level is ACL0. */
    ATL0 = 0,
    /**< Indicates that the authentication capability level is ACL1. */
    ATL1 = 10000,
    /**< Indicates that the authentication capability level is ACL2. */
    ATL2 = 20000,
    /**< Indicates that the authentication capability level is ACL3. */
    ATL3 = 30000,
    /**< Indicates that the authentication capability level is ACL4. */
    ATL4 = 40000,
};

/**
 * @brief Indicates executor information.
 *
 * @since 3.2
 * @version 2.0
 */
struct ExecutorInfo {
    /**< Indicates the sensor ID, which must be unique within the driver. */
    unsigned short sensorId;
    /**< Indicates the executor matcher. */
    unsigned int executorMatcher;
    /**< Indicates the max acl of template. See @{AuthenticationCapabilityLevel}. */
    unsigned int maxTemplateAcl;
    /**< Indicates the executor role. See @{ExecutorRole}. */
    int executorRole;
    /**< Indicates the auth type. See @{AuthType}. */
    int authType;
    /**< Indicates the executor secure level. See @{ExecutorSecureLevel}. */
    int esl;
    /**< Indicates the public key of the executor. */
    unsigned char[] publicKey;
    /**< Indicates extra information. */
    unsigned char[] extraInfo;
};

/**
 * @brief Enumerates prompt codes.
 *
 * @since 3.2
 * @version 1.2
 */
enum FingerprintTipsCode : int {
    /**< Indicates that the image acquired is good. */
    FINGERPRINT_AUTH_TIP_GOOD = 0,
    /**< Indicates that the fingerprint image is too noisy due to suspected or detected dirt on sensor. */
    FINGERPRINT_AUTH_TIP_DIRTY = 1,
    /**< Indicates that only a partial fingerprint image is detected. */
    FINGERPRINT_AUTH_TIP_INSUFFICIENT = 2,
    /**< Indicates that only a partial fingerprint image is detected. */
    FINGERPRINT_AUTH_TIP_PARTIAL = 3,
    /**< Indicates that the fingerprint image is incomplete due to quick motion. */
    FINGERPRINT_AUTH_TIP_TOO_FAST = 4,
    /**< Indicates that the fingerprint image is unreadable due to lack of motion. */
    FINGERPRINT_AUTH_TIP_TOO_SLOW = 5,
    /**< Indicates that the finger is down. */
    FINGERPRINT_AUTH_TIP_FINGER_DOWN = 6,
    /**< Indicates that the finger is up. */
    FINGERPRINT_AUTH_TIP_FINGER_UP = 7,
    /**< Indicates that a single auth result. The authentication result is carried in a json
        character string: {"authResult":1,"authRemainAttempts":3,"lockoutDuration":0} */
    FINGERPRINT_AUTH_TIP_SINGLE_AUTH_RESULT = 8,
    /**< The vendor may add a custom fingerprint auth tip after this. */
    VENDOR_FINGERPRINT_AUTH_TIP_BEGIN = 10000
};

/**
 * @brief Enumerates get Property types.
 *
 * @since 4.0
 * @version 1.1
 */
enum GetPropertyType : int {
    /**< Indicates that the property to get is auth sub type. */
    AUTH_SUB_TYPE = 1,
    /**< Indicates that the property to get is lockout duration. */
    LOCKOUT_DURATION = 2,
    /**< Indicates that the property to get is remain attempts. */
    REMAIN_ATTEMPTS = 3,
    /**< Indicates that the property to get is enroll progress. */
    ENROLL_PROGRESS = 4,
    /**< Indicates that the property to get is sensor info. */
    SENSOR_INFO = 5
};

/**
 * @brief Indicates executor property.
 *
 * @since 4.0
 * @version 1.1
 */
struct Property {
    /**< Indicates auth sub type. */
    unsigned long authSubType;
    /**< Indicates lockout duration. */
    int lockoutDuration;
    /**< Indicates remain attempts. */
    int remainAttempts;
    /**< Indicates enroll progress. */
    String enrollmentProgress;
    /**< Indicates sensor info. */
    String sensorInfo;
};

/**
 * @brief Enumerates sa command ids.
 *
 * @since 4.0
 * @version 1.1
 */
enum SaCommandId : int {
    /**< Indicates that the sa command is enable sensor illumination. */
    ENABLE_SENSOR_ILLUMINATION = 1,
    /**< Indicates that the sa command is disable sensor illumination. */
    DISABLE_SENSOR_ILLUMINATION = 2,
    /**< Indicates that the sa command is turn on sensor illumination. */
    TURN_ON_SENSOR_ILLUMINATION = 3,
    /**< Indicates that the sa command is turn off sensor illumination. */
    TURN_OFF_SENSOR_ILLUMINATION = 4,
};

/**
 * @brief Sa command parameter for enable sensor illumination.
 *
 * @since 4.0
 * @version 1.1
 */
struct SaCommandParamEnableSensorIllumination {
    /**< Indicates that highlight circle center x-coordinate per thousand to screen width. */
    unsigned int centerX;
    /**< Indicates that highlight circle center y-coordinate per thousand to screen height. */
    unsigned int centerY;
    /**< Indicates that highlight circle radius, in px. */
    unsigned int radius;
    /**< Indicates that highlight brightness. */
    unsigned int brightness;
    /**< Indicates that highlight color. */
    unsigned int color;
};

/**
 * @brief Indicates sa command parameter none.
 *
 * @since 4.0
 * @version 1.1
 */
struct SaCommandParamNone {
};

/**
 * @brief Indicates sa command parameter.
 *
 * @since 4.0
 * @version 1.1
 */
union SaCommandParam {
    /**< Indicates that sa command parameter is none. See {@link SaCommandParamNone}. */
    struct SaCommandParamNone none;
    /**< Indicates that sa command parameter is enable sensor illumination. See {@link SaCommandParamEnableSensorIllumination}. */
    struct SaCommandParamEnableSensorIllumination enableSensorIllumination;
};

/**
 * @brief Indicates sa command.
 *
 * @since 4.0
 * @version 2.0
 */
struct SaCommand {
    /**< Indicates sa command id. See {@link SaCommandId}. */
    int id;
    /**< Indicates sa command parameter. See {@link SaCommandParam}. */
    union SaCommandParam param;
};

/**
 * @brief Enumerates driver command IDs.
 *
 * @since 5.0
 * @version 1.0
 */
enum DriverCommandId : int {
    /**< Indicates the command ID for locking the template. */
    LOCK_TEMPLATE = 1,
    /**< Indicates the command ID for unlocking the template. */
    UNLOCK_TEMPLATE = 2,
    /**< Indicates the command ID for init algorithm. */
    INIT_ALGORITHM = 3,
    /**< The vendor may add a custom command ID after this. */
    VENDOR_COMMAND_BEGIN = 10000
};
/** @} */